codigos = [ [{'codigo':'BDE'},{'tipo':'1' },{'mensagem':'Objeto entregue ao destinatário'}],
            [{'codigo':'BDE'},{'tipo':'2' },{'mensagem':'Carteiro não atendido - Entrega não realizada'}],
            [{'codigo':'BDE'},{'tipo':'3' },{'mensagem':'Remetente não retirou objeto na Unidade dos Correios'},{'extra':'Objeto em análise de destinação'}],
            [{'codigo':'BDE'},{'tipo':'4' },{'mensagem':'Cliente recusou-se a receber o objeto - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDE'},{'tipo':'5' },{'mensagem':'A entrega não pode ser efetuada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDE'},{'tipo':'6' },{'mensagem':'Cliente desconhecido no local - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDE'},{'tipo':'7' },{'mensagem':'Endereço incorreto - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDE'},{'tipo':'8' },{'mensagem':'Endereço incorreto - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDE'},{'tipo':'9' },{'mensagem':'Objeto ainda não chegou à unidade'},{'extra':'Por favor, aguarde'}],
            [{'codigo':'BDE'},{'tipo':'10'},{'mensagem':'Cliente mudou-se - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDE'},{'tipo':'12'},{'mensagem':'Remetente não retirou objeto na Unidade dos Correios'},{'extra':'Objeto em análise de destinação'}],
            [{'codigo':'BDE'},{'tipo':'13'},{'mensagem':'Objeto atingido por incêndio em unidade operacional'}],
            [{'codigo':'BDE'},{'tipo':'14'},{'mensagem':'Desistência de postagem pelo remetente'}],
            [{'codigo':'BDE'},{'tipo':'15'},{'mensagem':'Recebido na unidade de distribuição'},{'extra':'Por determinação judicial o objeto será entregue em até 7 dias'}],
            [{'codigo':'BDE'},{'tipo':'18'},{'mensagem':'Carteiro não atendido - Entrega não realizada'},{'extra':'Será realizada nova tentativa de entrega no sábado'}],
            [{'codigo':'BDE'},{'tipo':'19'},{'mensagem':'Endereço incorreto - Entrega não realizada'},{'extra':'Objeto sujeito a atraso na entrega ou a devolução ao remetente'}],
            [{'codigo':'BDE'},{'tipo':'20'},{'mensagem':'Carteiro não atendido - Entrega não realizada'},{'extra':'Será realizada nova tentativa de entrega'}],
            [{'codigo':'BDE'},{'tipo':'21'},{'mensagem':'Carteiro não atendido - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDE'},{'tipo':'22'},{'mensagem':'Objeto devolvido aos Correios'}],
            [{'codigo':'BDE'},{'tipo':'23'},{'mensagem':'Objeto entregue ao remetente'}],
            [{'codigo':'BDE'},{'tipo':'24'},{'mensagem':'Objeto disponível para retirada em Caixa Postal'}],
            [{'codigo':'BDE'},{'tipo':'25'},{'mensagem':'Empresa sem expediente - Entrega não realizada'},{'extra':'Entrega deverá ocorrer no próximo dia útil'}],
            [{'codigo':'BDE'},{'tipo':'26'},{'mensagem':'Destinatário não retirou objeto no prazo'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDE'},{'tipo':'28'},{'mensagem':'Objeto e/ou conteúdo avariado'}],
            [{'codigo':'BDE'},{'tipo':'29'},{'mensagem':'Objeto não localizado'}],
            [{'codigo':'BDE'},{'tipo':'30'},{'mensagem':'Saída não efetuada'},{'extra':'Em tratamento, aguarde.'}],
            [{'codigo':'BDE'},{'tipo':'32'},{'mensagem':'Objeto com data de entrega agendada'}],
            [{'codigo':'BDE'},{'tipo':'33'},{'mensagem':'A entrega não pode ser efetuada - Destinatário não apresentou documento exigido'}],
            [{'codigo':'BDE'},{'tipo':'34'},{'mensagem':'A entrega não pode ser efetuada - Logradouro com numeração irregular'},{'extra':'Objeto sujeito a atraso na entrega ou a devolução ao remetente'}],
            [{'codigo':'BDE'},{'tipo':'35'},{'mensagem':'Coleta ou entrega de objeto não efetuada'},{'extra':'Será realizada nova tentativa de coleta ou entrega'}],
            [{'codigo':'BDE'},{'tipo':'36'},{'mensagem':'Coleta ou entrega de objeto não efetuada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDE'},{'tipo':'37'},{'mensagem':'Objeto e/ou conteúdo avariado por acidente com veículo'}],
            [{'codigo':'BDE'},{'tipo':'38'},{'mensagem':'Objeto endereçado à empresa falida'},{'extra':'Objeto será encaminhado para entrega ao administrador judicial'}],
            [{'codigo':'BDE'},{'tipo':'39'},{'mensagem':'A entrega não pode ser efetuada'},{'extra':'Objeto em análise de destinação'}],
            [{'codigo':'BDE'},{'tipo':'40'},{'mensagem':'Não foi autorizada a entrada do objeto no país pelos órgãos fiscalizadores'},{'extra':'Objeto em análise de destinação - poderá ser devolvido ao remetente, encaminhado para refugo ou apreendido'}],
            [{'codigo':'BDE'},{'tipo':'41'},{'mensagem':'A entrega do objeto está condicionada à composição do lote'}],
            [{'codigo':'BDE'},{'tipo':'42'},{'mensagem':'Lote de objetos incompleto'},{'extra':'Em devolução ao remetente'}],
            [{'codigo':'BDE'},{'tipo':'43'},{'mensagem':'Objeto apreendido por órgão de fiscalização'},{'extra':'Objeto está em poder da autoridade competente'}],
            [{'codigo':'BDE'},{'tipo':'44'},{'mensagem':'Aguardando órgão anuente apresentar documentação fiscal'}],
            [{'codigo':'BDE'},{'tipo':'45'},{'mensagem':'Objeto recebido na unidade de distribuição'},{'extra':'Entrega prevista para o próximo dia útil'}],
            [{'codigo':'BDE'},{'tipo':'46'},{'mensagem':'Tentativa de entrega não efetuada'},{'extra':'Entrega prevista para o próximo dia útil'}],
            [{'codigo':'BDE'},{'tipo':'47'},{'mensagem':'Saída para entrega cancelada'},{'extra':'Será efetuada nova saída para entrega'}],
            [{'codigo':'BDE'},{'tipo':'48'},{'mensagem':'Retirada em Unidade dos Correios não autorizada pelo remetente'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDE'},{'tipo':'49'},{'mensagem':'As dimensões do objeto impossibilitam o tratamento e a entrega'},{'extra':'O objeto será devolvido ao remetente'}],
            [{'codigo':'BDE'},{'tipo':'50'},{'mensagem':'Objeto roubado'}],
            [{'codigo':'BDE'},{'tipo':'51'},{'mensagem':'Objeto roubado'}],
            [{'codigo':'BDE'},{'tipo':'52'},{'mensagem':'Objeto roubado'}],
            [{'codigo':'BDE'},{'tipo':'53'},{'mensagem':'Objeto reimpresso e reenviado'}],
            [{'codigo':'BDE'},{'tipo':'54'},{'mensagem':'Aguardando a guia de recolhimento para pagamento do ICMS Importação'},{'extra':'Por favor, aguarde.'}],
            [{'codigo':'BDE'},{'tipo':'55'},{'mensagem':'Solicitação de revisão do tributo'},{'extra':'Acesse Minhas Importações para acompanhamento do pedido de revisão'}],
            [{'codigo':'BDE'},{'tipo':'56'},{'mensagem':'Objeto com declaração aduaneira ausente ou incorreta'},{'extra':'Aguarde: objeto em tratamento e sujeito a devolução'}],
            [{'codigo':'BDE'},{'tipo':'57'},{'mensagem':'Revisão de tributo concluída - Objeto liberado'}],
            [{'codigo':'BDE'},{'tipo':'58'},{'mensagem':'Revisão de tributo concluída - Tributo alterado'},{'extra':'O valor do tributo pode ter aumentado ou diminuído'}],
            [{'codigo':'BDE'},{'tipo':'59'},{'mensagem':'Revisão de tributo concluída - Tributo mantido'},{'extra':'Poderá haver incidência de juros e multa'}],
            [{'codigo':'BDE'},{'tipo':'60'},{'mensagem':'Objeto encontra-se aguardando prazo para refugo'}],
            [{'codigo':'BDE'},{'tipo':'61'},{'mensagem':'Objeto refugado'},{'extra':'Devolução proibida por órgão anuente ou não contratada pelo remetente'}],
            [{'codigo':'BDE'},{'tipo':'62'},{'mensagem':'Em devolução à origem por determinação da Receita Federal'},{'extra':'Objeto poderá ser devolvido à origem ou encaminhado para refugo de acordo com orientação do remetente'}],
            [{'codigo':'BDE'},{'tipo':'66'},{'mensagem':'Área com distribuição sujeita a prazo diferenciado'},{'extra':'Restrição de entrega domiciliar temporária'}],
            [{'codigo':'BDE'},{'tipo':'67'},{'mensagem':'Objeto entregue ao destinatário'},{'extra':'Entrega realizada em endereço vizinho, conforme autorizado pelo remetente'}],
            [{'codigo':'BDE'},{'tipo':'68'},{'mensagem':'Objeto entregue na Caixa de Correios Inteligente'}],
            [{'codigo':'BDE'},{'tipo':'69'},{'mensagem':'Objeto ainda não chegou à unidade'},{'extra':'Por favor, aguarde'}],
            [{'codigo':'BDE'},{'tipo':'70'},{'mensagem':'Objeto entregue ao destinatário'}],
            [{'codigo':'BDE'},{'tipo':'71'},{'mensagem':'Objeto apreendido por: ANVISA/VIGILANCIA SANITARIA'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDE'},{'tipo':'72'},{'mensagem':'Objeto apreendido por: BOMBEIROS'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDE'},{'tipo':'73'},{'mensagem':'Objeto apreendido por: EXERCITO'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDE'},{'tipo':'74'},{'mensagem':'Objeto apreendido por: IBAMA'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDE'},{'tipo':'75'},{'mensagem':'Objeto apreendido por: POLICIA FEDERAL'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDE'},{'tipo':'76'},{'mensagem':'Objeto apreendido por: POLICIA CIVIL/MILITAR'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDE'},{'tipo':'77'},{'mensagem':'Evento RFB - Aguardando DTRAT'}],
            [{'codigo':'BDE'},{'tipo':'79'},{'mensagem':'POSTAGEM INEXISTENTE (RESERVADO DERAT)'}],
            [{'codigo':'BDE'},{'tipo':'80'},{'mensagem':'Objeto não localizado no fluxo postal'}],
            [{'codigo':'BDE'},{'tipo':'81'},{'mensagem':'Não foi autorizada a saída do objeto do país pelos órgãos fiscalizadores'},{'extra':'Objeto em análise de destinação - poderá ser devolvido ao remetente, encaminhado para refugo ou apreendido'}],
            [{'codigo':'BDE'},{'tipo':'82'},{'mensagem':'Necessário complementar endereço de entrega'},{'extra':'Acesse o Fale Conosco > Reclamação > Objeto em processo de desembaraço'}],
            [{'codigo':'BDE'},{'tipo':'83'},{'mensagem':'Ação necessária à liberação do objeto não realizada pelo cliente'},{'extra':'Objeto em análise de destinação - poderá ser devolvido ao remetente, encaminhado para refugo ou apreendido'}],
            [{'codigo':'BDE'},{'tipo':'84'},{'mensagem':'Verificando situação do objeto'},{'extra':'Por favor, aguarde'}],
            [{'codigo':'BDE'},{'tipo':'85'},{'mensagem':'Código do objeto fora do padrão'},{'extra':'Objeto será entregue sem rastreamento'}],
            [{'codigo':'BDE'},{'tipo':'86'},{'mensagem':'Objeto com conteúdo avariado'},{'extra':'Sem condições de entrega'}],
            [{'codigo':'BDE'},{'tipo':'87'},{'mensagem':'Objeto destinado a outro país'}],
            [{'codigo':'BDE'},{'tipo':'89'},{'mensagem':'Localidade desconhecida no Brasil'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDE'},{'tipo':'98'},{'mensagem':'Objeto não localizado no fluxo postal'}],
            [{'codigo':'BDI'},{'tipo':'1' },{'mensagem':'Objeto entregue ao destinatário'}],
            [{'codigo':'BDI'},{'tipo':'2' },{'mensagem':'Carteiro não atendido - Entrega não realizada'},{'extra':'Aguarde: objeto estará disponível para retirada na unidade a ser informada'}],
            [{'codigo':'BDI'},{'tipo':'3' },{'mensagem':'Remetente não retirou objeto na Unidade dos Correios'},{'extra':'Objeto em análise de destinação'}],
            [{'codigo':'BDI'},{'tipo':'4' },{'mensagem':'Cliente recusou-se a receber o objeto - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDI'},{'tipo':'5' },{'mensagem':'A entrega não pode ser efetuada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDI'},{'tipo':'6' },{'mensagem':'Cliente desconhecido no local - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDI'},{'tipo':'7' },{'mensagem':'Endereço incorreto - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDI'},{'tipo':'8' },{'mensagem':'Endereço incorreto - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDI'},{'tipo':'9' },{'mensagem':'Objeto ainda não chegou à unidade'},{'extra':'Por favor, aguarde'}],
            [{'codigo':'BDI'},{'tipo':'10'},{'mensagem':'Cliente mudou-se - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDI'},{'tipo':'12'},{'mensagem':'Remetente não retirou objeto na Unidade dos Correios'},{'extra':'Objeto em análise de destinação'}],
            [{'codigo':'BDI'},{'tipo':'13'},{'mensagem':'Objeto atingido por incêndio em unidade operacional'}],
            [{'codigo':'BDI'},{'tipo':'14'},{'mensagem':'Desistência de postagem pelo remetente'}],
            [{'codigo':'BDI'},{'tipo':'15'},{'mensagem':'Recebido na unidade de distribuição'},{'extra':'Por determinação judicial o objeto será entregue em até 7 dias'}],
            [{'codigo':'BDI'},{'tipo':'18'},{'mensagem':'Carteiro não atendido - Entrega não realizada'},{'extra':'Será realizada nova tentativa de entrega no sábado'}],
            [{'codigo':'BDI'},{'tipo':'19'},{'mensagem':'Endereço incorreto - Entrega não realizada'},{'extra':'Objeto sujeito a atraso na entrega ou a devolução ao remetente'}],
            [{'codigo':'BDI'},{'tipo':'20'},{'mensagem':'Carteiro não atendido - Entrega não realizada'},{'extra':'Será realizada nova tentativa de entrega'}],
            [{'codigo':'BDI'},{'tipo':'21'},{'mensagem':'Carteiro não atendido - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDI'},{'tipo':'22'},{'mensagem':'Objeto devolvido aos Correios'}],
            [{'codigo':'BDI'},{'tipo':'23'},{'mensagem':'Objeto entregue ao remetente'}],
            [{'codigo':'BDI'},{'tipo':'24'},{'mensagem':'Objeto disponível para retirada em Caixa Postal'}],
            [{'codigo':'BDI'},{'tipo':'25'},{'mensagem':'Empresa sem expediente - Entrega não realizada'},{'extra':'Entrega deverá ocorrer no próximo dia útil'}],
            [{'codigo':'BDI'},{'tipo':'26'},{'mensagem':'Destinatário não retirou objeto no prazo'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDI'},{'tipo':'28'},{'mensagem':'Objeto e/ou conteúdo avariado'}],
            [{'codigo':'BDI'},{'tipo':'29'},{'mensagem':'Objeto não localizado'}],
            [{'codigo':'BDI'},{'tipo':'30'},{'mensagem':'Saída não efetuada'},{'extra':'Em tratamento, aguarde.'}],
            [{'codigo':'BDI'},{'tipo':'32'},{'mensagem':'Objeto com data de entrega agendada'}],
            [{'codigo':'BDI'},{'tipo':'33'},{'mensagem':'A entrega não pode ser efetuada - Destinatário não apresentou documento exigido'}],
            [{'codigo':'BDI'},{'tipo':'34'},{'mensagem':'A entrega não pode ser efetuada - Logradouro com numeração irregular'},{'extra':'Objeto sujeito a atraso na entrega ou a devolução ao remetente'}],
            [{'codigo':'BDI'},{'tipo':'35'},{'mensagem':'Coleta ou entrega de objeto não efetuada'},{'extra':'Será realizada nova tentativa de coleta ou entrega'}],
            [{'codigo':'BDI'},{'tipo':'36'},{'mensagem':'Coleta ou entrega de objeto não efetuada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDI'},{'tipo':'37'},{'mensagem':'Objeto e/ou conteúdo avariado por acidente com veículo'}],
            [{'codigo':'BDI'},{'tipo':'38'},{'mensagem':'Objeto endereçado à empresa falida'},{'extra':'Objeto será encaminhado para entrega ao administrador judicial'}],
            [{'codigo':'BDI'},{'tipo':'39'},{'mensagem':'A entrega não pode ser efetuada'},{'extra':'Objeto em análise de destinação'}],
            [{'codigo':'BDI'},{'tipo':'40'},{'mensagem':'Não foi autorizada a entrada do objeto no país pelos órgãos fiscalizadores'},{'extra':'Objeto em análise de destinação - poderá ser devolvido ao remetente, encaminhado para refugo ou apreendido'}],
            [{'codigo':'BDI'},{'tipo':'41'},{'mensagem':'A entrega do objeto está condicionada à composição do lote'}],
            [{'codigo':'BDI'},{'tipo':'42'},{'mensagem':'Lote de objetos incompleto'},{'extra':'Em devolução ao remetente'}],
            [{'codigo':'BDI'},{'tipo':'43'},{'mensagem':'Objeto apreendido por órgão de fiscalização'},{'extra':'Objeto está em poder da autoridade competente'}],
            [{'codigo':'BDI'},{'tipo':'44'},{'mensagem':'Aguardando órgão anuente apresentar documentação fiscal'}],
            [{'codigo':'BDI'},{'tipo':'45'},{'mensagem':'Objeto recebido na unidade de distribuição'},{'extra':'Entrega prevista para o próximo dia útil'}],
            [{'codigo':'BDI'},{'tipo':'46'},{'mensagem':'Tentativa de entrega não efetuada'},{'extra':'Entrega prevista para o próximo dia útil'}],
            [{'codigo':'BDI'},{'tipo':'47'},{'mensagem':'Saída para entrega cancelada'},{'extra':'Será efetuada nova saída para entrega'}],
            [{'codigo':'BDI'},{'tipo':'48'},{'mensagem':'Retirada em Unidade dos Correios não autorizada pelo remetente'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDI'},{'tipo':'49'},{'mensagem':'As dimensões do objeto impossibilitam o tratamento e a entrega'},{'extra':'O objeto será devolvido ao remetente'}],
            [{'codigo':'BDI'},{'tipo':'50'},{'mensagem':'Objeto roubado'}],
            [{'codigo':'BDI'},{'tipo':'51'},{'mensagem':'Objeto roubado'}],
            [{'codigo':'BDI'},{'tipo':'52'},{'mensagem':'Objeto roubado'}],
            [{'codigo':'BDI'},{'tipo':'53'},{'mensagem':'Objeto reimpresso e reenviado'}],
            [{'codigo':'BDI'},{'tipo':'54'},{'mensagem':'Aguardando a guia de recolhimento para pagamento do ICMS Importação'},{'extra':'Por favor, aguarde.'}],
            [{'codigo':'BDI'},{'tipo':'55'},{'mensagem':'Solicitação de revisão do tributo'},{'extra':'Acesse Minhas Importações para acompanhamento do pedido de revisão'}],
            [{'codigo':'BDI'},{'tipo':'56'},{'mensagem':'Objeto com declaração aduaneira ausente ou incorreta'},{'extra':'Aguarde: objeto em tratamento e sujeito a devolução'}],
            [{'codigo':'BDI'},{'tipo':'57'},{'mensagem':'Revisão de tributo concluída - Objeto liberado'}],
            [{'codigo':'BDI'},{'tipo':'58'},{'mensagem':'Revisão de tributo concluída - Tributo alterado'},{'extra':'O valor do tributo pode ter aumentado ou diminuído'}],
            [{'codigo':'BDI'},{'tipo':'59'},{'mensagem':'Revisão de tributo concluída - Tributo mantido'},{'extra':'Poderá haver incidência de juros e multa'}],
            [{'codigo':'BDI'},{'tipo':'60'},{'mensagem':'Objeto encontra-se aguardando prazo para refugo'}],
            [{'codigo':'BDI'},{'tipo':'61'},{'mensagem':'Objeto refugado'},{'extra':'Devolução proibida por órgão anuente ou não contratada pelo remetente'}],
            [{'codigo':'BDI'},{'tipo':'62'},{'mensagem':'Em devolução à origem por determinação da Receita Federal'},{'extra':'Objeto poderá ser devolvido à origem ou encaminhado para refugo de acordo com orientação do remetente'}],
            [{'codigo':'BDI'},{'tipo':'66'},{'mensagem':'Área com distribuição sujeita a prazo diferenciado'},{'extra':'Restrição de entrega domiciliar temporária'}],
            [{'codigo':'BDI'},{'tipo':'67'},{'mensagem':'Objeto entregue ao destinatário'},{'extra':'Entrega realizada em endereço vizinho, conforme autorizado pelo remetente'}],
            [{'codigo':'BDI'},{'tipo':'68'},{'mensagem':'Objeto entregue na Caixa de Correios Inteligente'}],
            [{'codigo':'BDI'},{'tipo':'69'},{'mensagem':'Objeto ainda não chegou à unidade'},{'extra':'Por favor, aguarde'}],
            [{'codigo':'BDI'},{'tipo':'70'},{'mensagem':'Objeto entregue ao destinatário'}],
            [{'codigo':'BDI'},{'tipo':'71'},{'mensagem':'Objeto apreendido por: ANVISA/VIGILANCIA SANITARIA'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDI'},{'tipo':'72'},{'mensagem':'Objeto apreendido por: BOMBEIROS'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDI'},{'tipo':'73'},{'mensagem':'Objeto apreendido por: EXERCITO'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDI'},{'tipo':'74'},{'mensagem':'Objeto apreendido por: IBAMA'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDI'},{'tipo':'75'},{'mensagem':'Objeto apreendido por: POLICIA FEDERAL'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDI'},{'tipo':'76'},{'mensagem':'Objeto apreendido por: POLICIA CIVIL/MILITAR'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDI'},{'tipo':'77'},{'mensagem':'Evento RFB - Aguardando DTRAT'}],
            [{'codigo':'BDI'},{'tipo':'80'},{'mensagem':'Objeto não localizado no fluxo postal'}],
            [{'codigo':'BDI'},{'tipo':'81'},{'mensagem':'Não foi autorizada a saída do objeto do país pelos órgãos fiscalizadores'},{'extra':'Objeto em análise de destinação - poderá ser devolvido ao remetente, encaminhado para refugo ou apreendido'}],
            [{'codigo':'BDI'},{'tipo':'82'},{'mensagem':'Necessário complementar endereço de entrega'},{'extra':'Acesse o Fale Conosco > Reclamação > Objeto em processo de desembaraço'}],
            [{'codigo':'BDI'},{'tipo':'83'},{'mensagem':'Ação necessária à liberação do objeto não realizada pelo cliente'},{'extra':'Objeto em análise de destinação - poderá ser devolvido ao remetente, encaminhado para refugo ou apreendido'}],
            [{'codigo':'BDI'},{'tipo':'84'},{'mensagem':'Verificando situação do objeto'},{'extra':'Por favor, aguarde'}],
            [{'codigo':'BDI'},{'tipo':'85'},{'mensagem':'Código do objeto fora do padrão'},{'extra':'Objeto será entregue sem rastreamento'}],
            [{'codigo':'BDI'},{'tipo':'86'},{'mensagem':'Objeto com conteúdo avariado'},{'extra':'Sem condições de entrega'}],
            [{'codigo':'BDI'},{'tipo':'87'},{'mensagem':'Objeto destinado a outro país'}],
            [{'codigo':'BDI'},{'tipo':'89'},{'mensagem':'Localidade desconhecida no Brasil'},{'extra':'O objeto será devolvido ao remetente'}],
            [{'codigo':'BDI'},{'tipo':'98'},{'mensagem':'Objeto não localizado no fluxo postal.'}],
            [{'codigo':'BDR'},{'tipo':'1' },{'mensagem':'Objeto entregue ao destinatário'}],
            [{'codigo':'BDR'},{'tipo':'2' },{'mensagem':'Carteiro não atendido - Entrega não realizada'},{'extra':'Aguarde: objeto estará disponível para retirada na unidade a ser informada'}],
            [{'codigo':'BDR'},{'tipo':'3' },{'mensagem':'Remetente não retirou objeto na Unidade dos Correios'},{'extra':'Objeto em análise de destinação'}],
            [{'codigo':'BDR'},{'tipo':'4' },{'mensagem':'Cliente recusou-se a receber o objeto - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDR'},{'tipo':'5' },{'mensagem':'A entrega não pode ser efetuada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDR'},{'tipo':'6' },{'mensagem':'Cliente desconhecido no local - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDR'},{'tipo':'7' },{'mensagem':'Endereço incorreto - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDR'},{'tipo':'8' },{'mensagem':'Endereço incorreto - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDR'},{'tipo':'9' },{'mensagem':'Objeto ainda não chegou à unidade'},{'extra':'Por favor, aguarde'}],
            [{'codigo':'BDR'},{'tipo':'10'},{'mensagem':'Cliente mudou-se - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDR'},{'tipo':'12'},{'mensagem':'Remetente não retirou objeto na Unidade dos Correios'},{'extra':'Objeto em análise de destinação'}],
            [{'codigo':'BDR'},{'tipo':'13'},{'mensagem':'Objeto atingido por incêndio em unidade operacional'}],
            [{'codigo':'BDR'},{'tipo':'14'},{'mensagem':'Desistência de postagem pelo remetente'}],
            [{'codigo':'BDR'},{'tipo':'15'},{'mensagem':'Recebido na unidade de distribuição'},{'extra':'Por determinação judicial o objeto será entregue em até 7 dias'}],
            [{'codigo':'BDR'},{'tipo':'18'},{'mensagem':'Carteiro não atendido - Entrega não realizada'},{'extra':'Será realizada nova tentativa de entrega no sábado'}],
            [{'codigo':'BDR'},{'tipo':'19'},{'mensagem':'Endereço incorreto - Entrega não realizada'},{'extra':'Objeto sujeito a atraso na entrega ou a devolução ao remetente'}],
            [{'codigo':'BDR'},{'tipo':'20'},{'mensagem':'Carteiro não atendido - Entrega não realizada'},{'extra':'Será realizada nova tentativa de entrega'}],
            [{'codigo':'BDR'},{'tipo':'21'},{'mensagem':'Carteiro não atendido - Entrega não realizada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDR'},{'tipo':'22'},{'mensagem':'Objeto devolvido aos Correios'}],
            [{'codigo':'BDR'},{'tipo':'23'},{'mensagem':'Objeto entregue ao remetente'}],
            [{'codigo':'BDR'},{'tipo':'24'},{'mensagem':'Objeto disponível para retirada em Caixa Postal'}],
            [{'codigo':'BDR'},{'tipo':'25'},{'mensagem':'Empresa sem expediente - Entrega não realizada'},{'extra':'Entrega deverá ocorrer no próximo dia útil'}],
            [{'codigo':'BDR'},{'tipo':'26'},{'mensagem':'Destinatário não retirou objeto no prazo'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDR'},{'tipo':'28'},{'mensagem':'Objeto e/ou conteúdo avariado'}],
            [{'codigo':'BDR'},{'tipo':'29'},{'mensagem':'Objeto não localizado'}],
            [{'codigo':'BDR'},{'tipo':'30'},{'mensagem':'Saída não efetuada'},{'extra':'Em tratamento, aguarde.'}],
            [{'codigo':'BDR'},{'tipo':'31'},{'mensagem':'Pagamento confirmado'},{'extra':'Entrega em até 40 dias úteis'}],
            [{'codigo':'BDR'},{'tipo':'32'},{'mensagem':'Objeto com data de entrega agendada'}],
            [{'codigo':'BDR'},{'tipo':'33'},{'mensagem':'A entrega não pode ser efetuada - Destinatário não apresentou documento exigido'}],
            [{'codigo':'BDR'},{'tipo':'34'},{'mensagem':'A entrega não pode ser efetuada - Logradouro com numeração irregular'},{'extra':'Objeto sujeito a atraso na entrega ou a devolução ao remetente'}],
            [{'codigo':'BDR'},{'tipo':'35'},{'mensagem':'Coleta ou entrega de objeto não efetuada'},{'extra':'Será realizada nova tentativa de coleta ou entrega'}],
            [{'codigo':'BDR'},{'tipo':'36'},{'mensagem':'Coleta ou entrega de objeto não efetuada'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDR'},{'tipo':'37'},{'mensagem':'Objeto e/ou conteúdo avariado por acidente com veículo'}],
            [{'codigo':'BDR'},{'tipo':'38'},{'mensagem':'Objeto endereçado à empresa falida'},{'extra':'Objeto será encaminhado para entrega ao administrador judicial'}],
            [{'codigo':'BDR'},{'tipo':'39'},{'mensagem':'A entrega não pode ser efetuada'},{'extra':'Objeto em análise de destinação'}],
            [{'codigo':'BDR'},{'tipo':'40'},{'mensagem':'Não foi autorizada a entrada do objeto no país pelos órgãos fiscalizadores'},{'extra':'Objeto em análise de destinação - poderá ser devolvido ao remetente, encaminhado para refugo ou apreendido'}],
            [{'codigo':'BDR'},{'tipo':'41'},{'mensagem':'A entrega do objeto está condicionada à composição do lote'}],
            [{'codigo':'BDR'},{'tipo':'42'},{'mensagem':'Lote de objetos incompleto'},{'extra':'Em devolução ao remetente'}],
            [{'codigo':'BDR'},{'tipo':'43'},{'mensagem':'Objeto apreendido por órgão de fiscalização'},{'extra':'Objeto está em poder da autoridade competente'}],
            [{'codigo':'BDR'},{'tipo':'44'},{'mensagem':'Aguardando órgão anuente apresentar documentação fiscal'}],
            [{'codigo':'BDR'},{'tipo':'45'},{'mensagem':'Objeto recebido na unidade de distribuição'},{'extra':'Entrega prevista para o próximo dia útil'}],
            [{'codigo':'BDR'},{'tipo':'46'},{'mensagem':'Tentativa de entrega não efetuada'},{'extra':'Entrega prevista para o próximo dia útil'}],
            [{'codigo':'BDR'},{'tipo':'47'},{'mensagem':'Saída para entrega cancelada'},{'extra':'Será efetuada nova saída para entrega'}],
            [{'codigo':'BDR'},{'tipo':'48'},{'mensagem':'Retirada em Unidade dos Correios não autorizada pelo remetente'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BDR'},{'tipo':'49'},{'mensagem':'As dimensões do objeto impossibilitam o tratamento e a entrega'},{'extra':'O objeto será devolvido ao remetente'}],
            [{'codigo':'BDR'},{'tipo':'50'},{'mensagem':'Objeto roubado'}],
            [{'codigo':'BDR'},{'tipo':'51'},{'mensagem':'Objeto roubado'}],
            [{'codigo':'BDR'},{'tipo':'52'},{'mensagem':'Objeto roubado'}],
            [{'codigo':'BDR'},{'tipo':'53'},{'mensagem':'Objeto reimpresso e reenviado'}],
            [{'codigo':'BDR'},{'tipo':'54'},{'mensagem':'Aguardando a guia de recolhimento para pagamento do ICMS Importação'},{'extra':'Por favor, aguarde.'}],
            [{'codigo':'BDR'},{'tipo':'55'},{'mensagem':'Solicitação de revisão do tributo'},{'extra':'Acesse Minhas Importações para acompanhamento do pedido de revisão'}],
            [{'codigo':'BDR'},{'tipo':'56'},{'mensagem':'Objeto com declaração aduaneira ausente ou incorreta'},{'extra':'Aguarde: objeto em tratamento e sujeito a devolução'}],
            [{'codigo':'BDR'},{'tipo':'57'},{'mensagem':'Revisão de tributo concluída - Objeto liberado'}],
            [{'codigo':'BDR'},{'tipo':'58'},{'mensagem':'Revisão de tributo concluída - Tributo alterado'},{'extra':'O valor do tributo pode ter aumentado ou diminuído'}],
            [{'codigo':'BDR'},{'tipo':'59'},{'mensagem':'Revisão de tributo concluída - Tributo mantido'},{'extra':'Poderá haver incidência de juros e multa'}],
            [{'codigo':'BDR'},{'tipo':'60'},{'mensagem':'Objeto encontra-se aguardando prazo para refugo'}],
            [{'codigo':'BDR'},{'tipo':'61'},{'mensagem':'Objeto refugado'},{'extra':'Devolução proibida por órgão anuente ou não contratada pelo remetente'}],
            [{'codigo':'BDR'},{'tipo':'62'},{'mensagem':'Em devolução à origem por determinação da Receita Federal'},{'extra':'Objeto poderá ser devolvido à origem ou encaminhado para refugo de acordo com orientação do remetente'}],
            [{'codigo':'BDR'},{'tipo':'63'},{'mensagem':'Pagamento não efetuado no prazo'},{'extra':'Objeto em análise de destinação'}],
            [{'codigo':'BDR'},{'tipo':'64'},{'mensagem':'Solicitação de dados não atendida'},{'extra':'O objeto será devolvido ao remetente'}],
            [{'codigo':'BDR'},{'tipo':'66'},{'mensagem':'Área com distribuição sujeita a prazo diferenciado'},{'extra':'Restrição de entrega domiciliar temporária'}],
            [{'codigo':'BDR'},{'tipo':'67'},{'mensagem':'Objeto entregue ao destinatário'},{'extra':'Entrega realizada em endereço vizinho, conforme autorizado pelo remetente'}],
            [{'codigo':'BDR'},{'tipo':'68'},{'mensagem':'Objeto entregue na Caixa de Correios Inteligente'}],
            [{'codigo':'BDR'},{'tipo':'69'},{'mensagem':'Objeto ainda não chegou à unidade'},{'extra':'Por favor, aguarde'}],
            [{'codigo':'BDR'},{'tipo':'70'},{'mensagem':'Objeto entregue ao destinatário'}],
            [{'codigo':'BDR'},{'tipo':'71'},{'mensagem':'Objeto apreendido por: ANVISA/VIGILANCIA SANITARIA'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDR'},{'tipo':'72'},{'mensagem':'Objeto apreendido por: BOMBEIROS'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDR'},{'tipo':'73'},{'mensagem':'Objeto apreendido por: EXERCITO'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDR'},{'tipo':'74'},{'mensagem':'Objeto apreendido por: IBAMA'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDR'},{'tipo':'75'},{'mensagem':'Objeto apreendido por: POLICIA FEDERAL'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDR'},{'tipo':'76'},{'mensagem':'Objeto apreendido por: POLICIA CIVIL/MILITAR'},{'extra':'O objeto está em poder da autoridade competente'}],
            [{'codigo':'BDR'},{'tipo':'77'},{'mensagem':'Evento RFB - Aguardando DTRAT'}],
            [{'codigo':'BDR'},{'tipo':'79'},{'mensagem':'POSTAGEM INEXISTENTE'}],
            [{'codigo':'BDR'},{'tipo':'80'},{'mensagem':'Objeto não localizado no fluxo postal'}],
            [{'codigo':'BDR'},{'tipo':'81'},{'mensagem':'Não foi autorizada a saída do objeto do país pelos órgãos fiscalizadores'},{'extra':'Objeto em análise de destinação - poderá ser devolvido ao remetente, encaminhado para refugo ou apreendido'}],
            [{'codigo':'BDR'},{'tipo':'82'},{'mensagem':'Necessário complementar endereço de entrega'},{'extra':'Acesse o Fale Conosco > Reclamação > Objeto em processo de desembaraço'}],
            [{'codigo':'BDR'},{'tipo':'83'},{'mensagem':'Ação necessária à liberação do objeto não realizada pelo cliente'},{'extra':'Objeto em análise de destinação - poderá ser devolvido ao remetente, encaminhado para refugo ou apreendido'}],
            [{'codigo':'BDR'},{'tipo':'84'},{'mensagem':'Verificando situação do objeto'},{'extra':'Por favor, aguarde'}],
            [{'codigo':'BDR'},{'tipo':'85'},{'mensagem':'Código do objeto fora do padrão'},{'extra':'Objeto será entregue sem rastreamento'}],
            [{'codigo':'BDR'},{'tipo':'86'},{'mensagem':'Objeto com conteúdo avariado'},{'extra':'Sem condições de entrega'}],
            [{'codigo':'BDR'},{'tipo':'87'},{'mensagem':'Objeto destinado a outro país'}],
            [{'codigo':'BDR'},{'tipo':'89'},{'mensagem':'Localidade desconhecida no Brasil'},{'extra':'Objeto será devolvido ao remetente'}],
            [{'codigo':'BLQ'},{'tipo':'1' },{'mensagem':'Solicitação de suspensão de entrega recebida'},{'extra':'Solicitação realizada pelo contratante/remetente'}],
            [{'codigo':'BLQ'},{'tipo':'4' },{'mensagem':'Bloqueio'}],
            [{'codigo':'BLQ'},{'tipo':'5' },{'mensagem':'Solicitação de suspensão de entrega recebida'},{'extra':'Objeto deve retornar ao Centro Internacional'}],
            [{'codigo':'BLQ'},{'tipo':'11'},{'mensagem':'Solicitação de suspensão de entrega recebida'},{'extra':'Solicitação realizada pelo contratante/remetente'}],
            [{'codigo':'BLQ'},{'tipo':'21'},{'mensagem':'Solicitação de suspensão de entrega recebida'}],
            [{'codigo':'BLQ'},{'tipo':'22'},{'mensagem':'Solicitação de suspensão de entrega recebida'}],
            [{'codigo':'BLQ'},{'tipo':'24'},{'mensagem':'Desbloqueio de objeto indenizado'}],
            [{'codigo':'BLQ'},{'tipo':'30'},{'mensagem':'Bloqueio teste'}],
            [{'codigo':'BLQ'},{'tipo':'31'},{'mensagem':'Extravio varejo pós-indenizado'}],
            [{'codigo':'BLQ'},{'tipo':'41'},{'mensagem':'Bloqueio SEGOPE 4/1'}],
            [{'codigo':'BLQ'},{'tipo':'42'},{'mensagem':'Bloqueio SEGOPE 4/2'}],
            [{'codigo':'BLQ'},{'tipo':'44'},{'mensagem':'Desbloqueio de objeto com conteúdo proibido/perigoso'}],
            [{'codigo':'BLQ'},{'tipo':'51'},{'mensagem':'Objeto bloqueado por necessidade de revisão de impostos/tributos'}],
            [{'codigo':'BLQ'},{'tipo':'54'},{'mensagem':'Desbloqueio de objeto com revisão de impostos/tributos'}],
            [{'codigo':'BLQ'},{'tipo':'61'},{'mensagem':'Desbloqueado'}],
            [{'codigo':'CO' },{'tipo':'1' },{'mensagem':'Objeto coletado'}],
            [{'codigo':'CO' },{'tipo':'2' },{'mensagem':'A coletar'}],
            [{'codigo':'CO' },{'tipo':'3' },{'mensagem':'Coletando'}],
            [{'codigo':'CO' },{'tipo':'4' },{'mensagem':'Pedido Transferido'}],
            [{'codigo':'CO' },{'tipo':'5' },{'mensagem':'1ª Tentativa de Coleta'}],
            [{'codigo':'CO' },{'tipo':'6' },{'mensagem':'2ª Tentativa / Coleta Cancelada'}],
            [{'codigo':'CO' },{'tipo':'7' },{'mensagem':'Aguardando Objeto na Agência'}],
            [{'codigo':'CO' },{'tipo':'8' },{'mensagem':'Entregue'}],
            [{'codigo':'CO' },{'tipo':'9' },{'mensagem':'Coleta Cancelada'}],
            [{'codigo':'CO' },{'tipo':'10'},{'mensagem':'Desistência do Cliente ECT'}],
            [{'codigo':'CO' },{'tipo':'11'},{'mensagem':'Objeto Sinistrado'}],
            [{'codigo':'CO' },{'tipo':'12'},{'mensagem':'Aguardando Objeto de Entrega'}],
            [{'codigo':'CO' },{'tipo':'13'},{'mensagem':'Objeto não coletado'}],
            [{'codigo':'CO' },{'tipo':'14'},{'mensagem':'Transformado em e-ticket'}],
            [{'codigo':'DO' },{'tipo':'1' },{'mensagem':'Objeto encaminhado'}],
            [{'codigo':'DO' },{'tipo':'2' },{'mensagem':'Objeto encaminhado'}],
            [{'codigo':'EST'},{'tipo':'1' },{'mensagem':'Favor desconsiderar a informação anterior'}],
            [{'codigo':'EST'},{'tipo':'2' },{'mensagem':'Favor desconsiderar a informação anterior'}],
            [{'codigo':'EST'},{'tipo':'3' },{'mensagem':'Favor desconsiderar a informação anterior'}],
            [{'codigo':'EST'},{'tipo':'4' },{'mensagem':'Favor desconsiderar a informação anterior'}],
            [{'codigo':'EST'},{'tipo':'5' },{'mensagem':'Favor desconsiderar a informação anterior'}],
            [{'codigo':'EST'},{'tipo':'6' },{'mensagem':'Favor desconsiderar a informação anterior'}],
            [{'codigo':'EST'},{'tipo':'9' },{'mensagem':'Favor desconsiderar a informação anterior'}],
            [{'codigo':'FC' },{'tipo':'1' },{'mensagem':'Objeto será devolvido por solicitação do contratante/remetente'},{'extra':'Em tratamento, aguarde.'}],
            [{'codigo':'FC' },{'tipo':'2' },{'mensagem':'Objeto com data de entrega agendada'},{'extra':'Em tratamento, aguarde.'}],
            [{'codigo':'FC' },{'tipo':'3' },{'mensagem':'Objeto mal encaminhado'},{'extra':'Encaminhamento a ser corrigido'}],
            [{'codigo':'FC' },{'tipo':'4' },{'mensagem':'Endereço incorreto - Entrega não realizada'},{'extra':'Objeto sujeito a atraso na entrega ou a devolução ao remetente'}],
            [{'codigo':'FC' },{'tipo':'5' },{'mensagem':'Objeto devolvido aos Correios'}],
            [{'codigo':'FC' },{'tipo':'7' },{'mensagem':'Empresa sem expediente - Entrega não realizada'},{'extra':'Entrega deverá ocorrer no próximo dia útil'}],
            [{'codigo':'FC' },{'tipo':'8' },{'mensagem':'Área com distribuição sujeita a prazo diferenciado'},{'extra':'Restrição de entrega domiciliar temporária'}],
            [{'codigo':'FC' },{'tipo':'9' },{'mensagem':'Remetente não retirou objeto na Unidade dos Correios'},{'extra':'Objeto em análise de destinação'}],
            [{'codigo':'FC' },{'tipo':'10'},{'mensagem':'Objeto recebido na unidade de distribuição'},{'extra':'Entrega deverá ocorrer no próximo dia útil'}],
            [{'codigo':'FC' },{'tipo':'11'},{'mensagem':'Objeto destruído com autorização do remetente'}],
            [{'codigo':'FC' },{'tipo':'12'},{'mensagem':'Objeto encaminhado para fiscalização - ANVISA'}],
            [{'codigo':'FC' },{'tipo':'13'},{'mensagem':'Fiscalizado ANATEL'},{'extra':'Seguir orientações do site da ANATEL. Prazo: 10 dias corridos'}],
            [{'codigo':'FC' },{'tipo':'19'},{'mensagem':'Objeto encaminhado para fiscalização - ANATEL'}],
            [{'codigo':'FC' },{'tipo':'24'},{'mensagem':'Em fiscalização pela Receita Federal'}],
            [{'codigo':'FC' },{'tipo':'26'},{'mensagem':'RFB - Objeto Tributado - Emissão da nota de tributação'}],
            [{'codigo':'FC' },{'tipo':'27'},{'mensagem':'Objeto encaminhado para emissão de DSI'}],
            [{'codigo':'FC' },{'tipo':'29'},{'mensagem':'Objeto encaminhado para apreensão'}],
            [{'codigo':'FC' },{'tipo':'31'},{'mensagem':'Aguardando autorização para exportação'}],
            [{'codigo':'FC' },{'tipo':'32'},{'mensagem':'Objeto encaminhado para fiscalização - INMETRO'}],
            [{'codigo':'FC' },{'tipo':'33'},{'mensagem':'Objeto encaminhado para fiscalização - Polícia Federal'}],
            [{'codigo':'FC' },{'tipo':'34'},{'mensagem':'Objeto encaminhado para fiscalização - VIGIAGRO'}],
            [{'codigo':'FC' },{'tipo':'35'},{'mensagem':'Objeto encaminhado para fiscalização - Exército'}],
            [{'codigo':'FC' },{'tipo':'37'},{'mensagem':'Objeto encaminhado para fiscalização - IBAMA'}],
            [{'codigo':'FC' },{'tipo':'41'},{'mensagem':'Problemas na documentação do objeto'},{'extra':'Procure a agência de postagem em até 2 dias úteis'}],
            [{'codigo':'FC' },{'tipo':'42'},{'mensagem':'Objeto contém líquido, impossibilitando seu transporte'},{'extra':'Em tratamento, aguarde'}],
            [{'codigo':'FC' },{'tipo':'47'},{'mensagem':'Objeto será devolvido por solicitação do contratante/remetente'},{'extra':'Em tratamento, aguarde.'}],
            [{'codigo':'FC' },{'tipo':'51'},{'mensagem':'Objeto roubado'}],
            [{'codigo':'FC' },{'tipo':'55'},{'mensagem':'Encomenda unitizada finalizada'}],
            [{'codigo':'LDI'},{'tipo':'1' },{'mensagem':'Objeto aguardando retirada no endereço indicado'},{'extra':'Para retirá-lo, é preciso informar o código do objeto e apresentar documentação que comprove ser o destinatário ou pessoa por ele oficialmente autorizada.'}],
            [{'codigo':'LDI'},{'tipo':'2' },{'mensagem':'Objeto disponível para retirada em Caixa Postal'}],
            [{'codigo':'LDI'},{'tipo':'3' },{'mensagem':'Objeto aguardando retirada no endereço indicado'},{'extra':'Para retirá-lo, é preciso informar o código do objeto e apresentar documentação que comprove ser o destinatário ou pessoa por ele oficialmente autorizada.'}],
            [{'codigo':'LDI'},{'tipo':'4' },{'mensagem':'Objeto aguardando retirada no endereço indicado'},{'extra':'Para retirá-lo, é preciso informar o código do objeto e apresentar documentação que comprove ser o destinatário ou pessoa por ele oficialmente autorizada.'}],
            [{'codigo':'LDI'},{'tipo':'11'},{'mensagem':'Objeto encaminhado para retirada no endereço indicado'},{'extra':'Para retirá-lo, é preciso informar o código do objeto.'}],
            [{'codigo':'LDI'},{'tipo':'13'},{'mensagem':'Objeto encaminhado para retirada no endereço indicado'},{'extra':'Para retirá-lo, é preciso informar o código do objeto.'}],
            [{'codigo':'LDI'},{'tipo':'14'},{'mensagem':'Objeto encaminhado para retirada no endereço indicado'},{'extra':'Para retirá-lo, é preciso informar o código do objeto.'}],
            [{'codigo':'OEC'},{'tipo':'1' },{'mensagem':'Objeto saiu para entrega ao destinatário'}],
            [{'codigo':'OEC'},{'tipo':'9' },{'mensagem':'Objeto saiu para entrega ao remetente'}],
            [{'codigo':'PAR'},{'tipo':'10'},{'mensagem':'Fiscalização aduaneira finalizada'}],
            [{'codigo':'PAR'},{'tipo':'11'},{'mensagem':'Aguardando pagamento'}],
            [{'codigo':'PAR'},{'tipo':'12'},{'mensagem':'Informações prestadas pelo cliente em análise'}],
            [{'codigo':'PAR'},{'tipo':'13'},{'mensagem':'Objeto devolvido ao país de origem'}],
            [{'codigo':'PAR'},{'tipo':'14'},{'mensagem':'Revisão de tributos solicitada pelo cliente'}],
            [{'codigo':'PAR'},{'tipo':'15'},{'mensagem':'Objeto recebido em'}],
            [{'codigo':'PAR'},{'tipo':'16'},{'mensagem':'Objeto recebido pelos Correios do Brasil'}],
            [{'codigo':'PAR'},{'tipo':'17'},{'mensagem':'Aguardando pagamento'}],
            [{'codigo':'PAR'},{'tipo':'18'},{'mensagem':'Objeto recebido na unidade de exportação no país de origem'}],
            [{'codigo':'PAR'},{'tipo':'19'},{'mensagem':'Fiscalização aduaneira finalizada no país de destino'}],
            [{'codigo':'PAR'},{'tipo':'20'},{'mensagem':'Objeto recebido pelos Correios do Brasil com embalagem danificada'},{'extra':'Por favor, aguarde'}],
            [{'codigo':'PAR'},{'tipo':'21'},{'mensagem':'Encaminhado para fiscalização aduaneira'}],
            [{'codigo':'PAR'},{'tipo':'22'},{'mensagem':'Encaminhado para fiscalização no país de destino'}],
            [{'codigo':'PAR'},{'tipo':'23'},{'mensagem':'Aguardando autorização da Receita Federal para devolução do objeto ao remetente'}],
            [{'codigo':'PAR'},{'tipo':'24'},{'mensagem':'Devolução autorizada pela Receita Federal'}],
            [{'codigo':'PAR'},{'tipo':'25'},{'mensagem':'Faltam informações. Sua ação é necessária'}],
            [{'codigo':'PAR'},{'tipo':'26'},{'mensagem':'Destinatário recusou o objeto'},{'extra':'Objeto em análise de destinação'}],
            [{'codigo':'PAR'},{'tipo':'27'},{'mensagem':'Despacho Postal pago na origem'}],
            [{'codigo':'PAR'},{'tipo':'28'},{'mensagem':'Encaminhado para a unidade de tratamento'}],
            [{'codigo':'PAR'},{'tipo':'29'},{'mensagem':'PAR 29'}],
            [{'codigo':'PAR'},{'tipo':'30'},{'mensagem':'Aguardando pagamento do despacho postal'}],
            [{'codigo':'PAR'},{'tipo':'31'},{'mensagem':'Pagamento confirmado'}],
            [{'codigo':'PAR'},{'tipo':'32'},{'mensagem':'Aguardando confirmação de pagamento pela operadora'}],
            [{'codigo':'PAR'},{'tipo':'33'},{'mensagem':'Pagamento não confirmado pela operadora'},{'extra':'Entre em contato com sua operadora'}],
            [{'codigo':'PAR'},{'tipo':'34'},{'mensagem':'Liberado sem tributação'}],
            [{'codigo':'PAR'},{'tipo':'40'},{'mensagem':'Devolução a pedido'},{'extra':'Cliente solicitou a devolução da encomenda'}],
            [{'codigo':'PAR'},{'tipo':'41'},{'mensagem':'Prazo de pagamento encerrado'},{'extra':'Objeto em análise de destinação'}],
            [{'codigo':'PAR'},{'tipo':'42'},{'mensagem':'Objeto liberado'}],
            [{'codigo':'PO' },{'tipo':'1' },{'mensagem':'Objeto postado'}],
            [{'codigo':'PO' },{'tipo':'9' },{'mensagem':'Objeto postado após o horário limite da unidade'},{'extra':'Sujeito a encaminhamento no próximo dia útil'}],
            [{'codigo':'RO' },{'tipo':'1' },{'mensagem':'Objeto encaminhado'}]];